### ISSUE TITLE
Dependencies unclear / not documented

### ISSUE THREAD

**Issue by StuAtGit** [librato/salt-state-test#2]
Trying to get this to run. Before even running, I did open the file and skim the imports. Then I installed the salt api, which seems sensible, and tried this:

stuart.smith@linux-6v07:~/workspace/salt-state-test> python test_salt_state.py -j ../salt-states/[......]/init.sls

(where [....] is a valid path to the init.sls file)

And got this:

Traceback (most recent call last):
  File "test_salt_state.py", line 24, in <module>
    from salt.config import _expand_glob_path
ImportError: cannot import name _expand_glob_path

I tried googling around to get the dependency for the above, but couldn't come up with anything.

**Comment by pcn** [comment]
What version of saltstack are you running?  I'm using 2015.5.2 at the moment, I believe.

**Comment by pcn** [comment]
I've just added dependency info to the README.md.

**Comment by StuAtGit** [comment]
Cool. I'll take a look at the version when I get back to the office. Thanks for updating! :)
